version: "3"

services: 
  valheim: 
    image: desidia26/valheim:latest
    cap_add:
      - sys_nice
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
      - "3000:80"
    environment:
      SERVER_PASS: 262626
      STATUS_HTTP: true
      WORLD_BUCKET: s3://valheim-state
      WORLD_NAME: AWholeNewWorld
      BEPINEX: true
      PRE_SERVER_RUN_HOOK: downloadMods
    restart: always
    volumes:
    - $HOME/.aws/credentials:/root/.aws/credentials:ro
    stop_grace_period: 2m
