version: "3"

services: 
  valheim: 
    image: desidia26/valheim
    cap_add:
      - sys_nice
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
      - "3000:80"
    environment:
      - SERVER_PASS=262626
      - STATUS_HTTP=true
    restart: always
    stop_grace_period: 2m
